version: "3.8"
services:
  mongo:
    image: mongo:7.0.0
    container_name: zorak_mongo_${ENVIRONMENT}
    env_file: .env
    volumes:
      - ./db:/data/db
    restart: always

  zorak:
    build: .
    image: zorak:${TAG}
    container_name: zorak_bot_${ENVIRONMENT}
    env_file: .env
    links:
      - "mongo:mongo"
    depends_on:
      - mongo
    restart: always
    volumes:
      - .:/code  # This line mounts your local directory to the /code directory inside the container
